name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  macos-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build -p stac-cli --release --all-features
      - name: Archive binary
        run: |
          ARCHIVE_FILE=stac-x86_64-apple-darwin.tar.gz
          tar czvf $ARCHIVE_FILE -C target/x86_64-apple-darwin/release stac
          shasum -a 256 $ARCHIVE_FILE > $ARCHIVE_FILE.sha256
      - name: "Upload binary"
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            *.tar.gz
            *.sha256

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - macos-x86_64
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
      - uses: actions/download-artifact@v3
        with:
          name: binaries
          path: binaries
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: binaries/*
